apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: data-catalog-app
data:
  custom.conf: |
    # CONNECTION
    listen_addresses = '*'
    
    # REPLICATION
    wal_level = logical             # minimal, archive, hot_standby, or logical (change requires restart)
    max_wal_senders = 100             # max number of walsender processes (change requires restart)
    #wal_keep_segments = 4          # in logfile segments, 16MB each; 0 disables
    #wal_sender_timeout = 60s       # in milliseconds; 0 disables
    max_replication_slots = 100       # max number of replication slots (change requires restart)
